### ISSUE TITLE
Manage ScaleIO as a persistent application

### ISSUE THREAD

**Issue by clintkitson** [codedellemc/roadmap#146]
This issue is tracking the ability to manage ScaleIO a persistent application per the typical methods that Mesos manages other persistent applications.

**Comment by dvonthenen** [comment]
This is in progress. I had a demo of an initial concept yesterday. Still need to polish somethings and implement a few others.

**Comment by victorock** [comment]
Though the MVP was already done for Compose at least: https://github.com/victorock/scaleio2-docker
