### ISSUE TITLE
Monitor ScaleIO and Prometheus

### ISSUE THREAD

**Issue by clintonskitson** [codedellemc/roadmap#164]
Integration monitoring from Prometheus to ScaleIO.

**Comment by mux23** [comment]
blog entry on monitoring ScaleIO with Prometheus published to blog.emccode.com drafts

**Comment by syepes** [comment]
@mux23 Where is this post? i can not find it

**Comment by mux23** [comment]
@syepes it's in the queue still, apparently. :) I'll ask around as to when it's supposed to get posted...

**Comment by syepes** [comment]
Now you can monitor ScaleIO with Prometheus _:-)_ https://github.com/syepes/sio2prom
