### ISSUE TITLE
PR: Implement Prometheus Metrics for ScaleIO

### ISSUE THREAD

**Issue by dvonthenen** [codedellemc/roadmap#182]
This work represents that Go application that will provide a shim layer to expose a Prometheus /metric endpoint and create the Prometheus pref counter objects for ScaleIO.

- [x] Create Kubernetes-ScaleIO-Prom project in GitHub
- [x] Add dependencies to project: goScaleIO, Logrus, Testify, Prometheus Client 
- [x] Implement Prometheus /metrics endpoint in REST
- [x] Mine ScaleIO Statistics object from StoragePools
- [x] Translate Statistic objects to Promethues Pref Counter Objects
- [x] Create the Dockerfile and image for this Endpoint
- [x] Create Kubernetes deployment YAML for consuming ScaleIO deployed using ScaleIO Native Driver
- [x] Create Kubernetes deplyoment YAML for consuming generic ScaleIO

Deliverable Date: 8/25

**Comment by dvonthenen** [comment]
You can find the repo here: https://github.com/dvonthenen/kubernetes-scaleio-prom

**Comment by dvonthenen** [comment]
Initial check in has been done... need to package and test.

**Comment by clintkitson** [comment]
👍

**Comment by dvonthenen** [comment]
Surprised it worked on the first shot! This is done!

Deployment YAMLs created and updated the README.md. Note this is not a full blown metrics implementation, but there are enough metrics collected (MVP) for this to be useful.
